"""
Django settings for comicsite project.

Generated by 'django-admin startproject' using Django 1.11.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
from .common_settings import *

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '#2g6xfo7*zfl&@!47adslek@52m7ne8h+&^s-s@@mwes$=^w-q'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['comics.jnduli.co.ke', 'www.comics.jnduli.co.ke']

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': 'comic_server',
            'USER': 'rookie_comic',
            'PASSWORD': 'proasskicmic4',
            'HOST': 'localhost',
            'PORT': '',
            #  'ENGINE': 'django.db.backends.sqlite3',
            #  'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
            }
        }

# directories for static files
ENV_PATH = '/var/www/static_files/'
MEDIA_ROOT = os.path.join(ENV_PATH, 'media/')
STATIC_ROOT = os.path.join(ENV_PATH, 'static/')

ANALYTICS_TRACKING_ID = 'UA-89300561-2'

DBBACKUP_STORAGE_OPTIONS = {'location': '/var/backups/comic_server'}
