version: "3.7"

services: 
  comic_server:
    build:
      context: ../
      dockerfile: Dockerfile
    image: comic_server_sqlite:latest
    restart: always
    container_name: comic_server_sqlite
    networks:
      - comic_server_sqlite_network
    environment:
      SECRET_KEY: "${SECRET_KEY}"
      DJANGO_SETTINGS_MODULE: "comicsite.production_settings"
      ALLOWED_HOSTS: "${ALLOWED_HOSTS}"
    volumes:
      - "${STATIC_FOLDER_PATH}:/var/www/static_files/:rw"
      - "${BACKUP_FOLDER_PATH}:/var/backups/comic_server/:rw"
    ports:
      - 127.0.0.1:9000:8000

networks:
  comic_server_sqlite_network:
    name: comic-server-docker-network
    driver: bridge
