# Generated by Django 3.2 on 2021-04-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sketch', '0002_remove_sketch_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sketch',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
