image: joyzoursky/python-chromedriver:3.6-xvfb-selenium

test:
  stage: test
  script:
    - apt-get update -qy
    - apt-get install -y python-dev python-pip
      # install this for functional tests
    - apt-get install chromium
    - pip install -r requirements.txt
    - cd comicsite
    - cp .env.example .env
    - python manage.py makemigrations
    - python manage.py migrate
    - python manage.py test
