# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-13 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comic',
            name='description',
        ),
        migrations.RemoveField(
            model_name='comic',
            name='title',
        ),
        migrations.RemoveField(
            model_name='concept',
            name='comicstrips_no',
        ),
        migrations.RemoveField(
            model_name='concept',
            name='environment',
        ),
        migrations.AddField(
            model_name='concept',
            name='description',
            field=models.TextField(default='created later on', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='concept',
            name='title',
            field=models.CharField(default='title', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='concept',
            name='characters_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='concept',
            name='conversation',
            field=models.TextField(null=True),
        ),
    ]
