# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-13 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0002_auto_20170813_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='characters_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='concept',
            name='conversation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
