# Generated by Django 2.1.5 on 2019-02-06 11:43

from django.db import migrations
from django.contrib.auth import get_user_model


class Migration(migrations.Migration):

    def updateComics(apps, schema_editor):
        User = get_user_model();
        # Get list of users and if count == 1, use this one
        # Otherwise set this to be the superuser who'll fix discrepancy later
        if User.objects.count() == 1:
            user = User.objects.get()
        else:
            # get the first superuser
            user = User.objects.filter(is_superuser=True)[0]

        Comic = apps.get_model('comics', 'Comic');
        for comic in Comic.objects.all():
            comic.user = user
            comic.save()

    dependencies = [
        ('comics', '0002_auto_20170909_0910'),
    ]

    operations = [
        migrations.RunPython(updateComics)
    ]
