# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-21 02:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0003_auto_20170813_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='sketch',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='comics.Sketch'),
        ),
        migrations.AlterField(
            model_name='sketch',
            name='concept',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='comics.Concept'),
        ),
    ]
