# Generated by Django 2.1.5 on 2019-02-06 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0003_auto_20190206_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comic',
            name='user',
        ),
    ]
