# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-01 03:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gimp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gimp',
            old_name='gimp',
            new_name='file_gimp',
        ),
    ]
