# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-01 05:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strip',
            name='concept',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='concept.Concept'),
        ),
    ]
