--- 
- name: Updating apt cache
  remote_user: "{{ user }}"
  become: true
  apt: update_cache=yes

- name: Installing required packages
  remote_user: "{{ user }}"
  become: true
  apt: name={{ item }} state=present
  with_items:
      - git
      - nginx
      - supervisor
      - postgresql
      - postgresql-contrib
      - python-psycopg2

