---
- hosts: my_server
  var_files:
    - vars.yml

  tasks:
  # copy project nginx set up to server
    - name: set up nginx config on server
      remote_user: {{ user }}
      become: true
      template:
        src=config/nginx/j2
        dest=/etc/nginx/sites-enabled/{{ project_name }}
      notify:
        - restart nginx

  handlers:
    - name: restart nginx
      remote_user: {{ user }}
      become: true
      service: name=nginx state=restarted
