---
- hosts: my_server
  vars_files:
      - vars.yml
  remote_user: "{{ user }}"
  become: true

  tasks:
      - name: Updating apt cache
        apt: update_cache=yes
      - name: Installing required packages
        apt: name={{ item }} state=present
        with_items:
            - git
            - nginx
            - supervisor
            - postgresql
            - postgresql-contrib

