# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-01 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concept', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
