# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-01 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concept', '0002_concept_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='date_published',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
