# Generated by Django 2.0 on 2018-03-31 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concept', '0003_concept_date_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='conversation_html',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
