# Generated by Django 2.0 on 2018-04-07 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concept', '0004_concept_conversation_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='public_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='concept',
            name='public_note_html',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
