# Generated by Django 2.2.13 on 2021-11-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concept', '0007_alter_concept_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
